export const FieldGroup = {
  GENERAL: 'GENERAL',
  ADDRESS: 'ADDRESS',
  CONTACT: 'CONTACT',
  DOCUMENT: 'DOCUMENT',
  BANK: 'BANK',
  FINANCIAL: 'FINANCIAL',
  PERSONNEL: 'PERSONNEL',
  CAPABILITY: 'CAPABILITY',
} as const;
