import { z } from 'zod'

import type { FormSchema } from '../types'

export const localCompanySchema: FormSchema = {
  id: 'vendor_company',
  title: 'Company Information',
  description: 'Provide general information about your company.',
  sections: [
    {
      id: 'general_info',
      title: 'General Information',
      fields: [
        {
          id: 'companyName',
          name: 'companyName',
          label: 'Company Name',
          type: 'text',
          placeholder: 'PT. Maju Mundur',
          required: true,
          grid: { xs: 12, md: 6 },
          helperText: 'Do not include company prefixes or legal entity names such as PT, CV, Ltd., Inc., etc. Please select the appropriate Business Type instead.',
        },
        {
          id: 'siteId',
          name: 'siteId',
          label: 'Site',
          type: 'autocomplete',
          required: true,
          grid: { xs: 12, md: 6 },
          lookupEndpoint: 'sites',
        },
        {
          id: 'businessTypeId',
          name: 'businessTypeId',
          label: 'Business Type',
          type: 'autocomplete',
          required: true,
          grid: { xs: 12, md: 6 },
          lookupEndpoint: 'business-entity-types',
        },
        {
          id: 'staffCount',
          name: 'staffCount',
          label: 'Staff Count',
          type: 'number',
          placeholder: 'e.g. 50',
          grid: { xs: 12, md: 6 },
        },
      ],
    },
    {
      id: 'address_info',
      title: 'Address Information',
      fields: [
        {
          id: 'address',
          name: 'address',
          label: 'Address',
          type: 'textarea',
          placeholder: 'Jl. Sudirman No. 123',
          required: true,
          grid: { xs: 12 },
        },
        {
          id: 'countryId',
          name: 'countryId',
          label: 'Country',
          type: 'autocomplete',
          required: true,
          grid: { xs: 12, md: 4 },
          lookupEndpoint: 'countries',
          defaultValue: 27,
          disabled: true,
        },
        {
          id: 'provinceId',
          name: 'provinceId',
          label: 'Province',
          type: 'autocomplete',
          required: true,
          grid: { xs: 12, md: 4 },
          lookupEndpoint: 'provinces',
          dependsOn: 'countryId',
          dependencyParam: 'countryId',
        },
        {
          id: 'cityId',
          name: 'cityId',
          label: 'City',
          type: 'autocomplete',
          required: true,
          grid: { xs: 12, md: 4 },
          lookupEndpoint: 'cities',
          dependsOn: 'provinceId',
          dependencyParam: 'provinceId',
        },
        {
          id: 'postalCode',
          name: 'postalCode',
          label: 'Postal Code',
          type: 'text',
          placeholder: '12345',
          grid: { xs: 12, md: 6 },
        },
        {
          id: 'website',
          name: 'website',
          label: 'Website',
          type: 'text',
          placeholder: 'https://company.com',
          validation: z.string().url().optional().or(z.literal('')),
          grid: { xs: 12, md: 6 },
        },
        {
          id: 'mapUrl',
          name: 'mapUrl',
          label: 'Google Maps URL',
          type: 'text',
          placeholder: 'https://maps.google.com/...',
          validation: z.string().url().optional().or(z.literal('')),
          grid: { xs: 12 },
        },
      ],
    },
  ],
}
