export enum WorkflowCode {
    VENDOR_REGISTRATION = 'VENDOR_REGISTRATION',
    VENDOR_UPDATE = 'VENDOR_UPDATE',
    DIGITAL_SIGNATURE = 'DIGITAL_SIGNATURE',
    PROPOSED_TO_REJECT = 'PROPOSED_TO_REJECT',
    DELETE_COMPANY_ACCOUNT = 'DELETE_COMPANY_ACCOUNT',
    REACTIVATION = 'REACTIVATION',
    BLACKLIST_UNBLACKLIST = 'BLACKLIST_UNBLACKLIST',
    ROLE_EXPIRED = 'ROLE_EXPIRED',
}
