"use client"

import React, { useMemo } from 'react';

import { DynamicFormContext } from './dynamic-form.context';
import type { DynamicFormContextValue } from './dynamic-form-context.interface';

export interface DynamicFormProviderProps {
  value: DynamicFormContextValue;
  children: React.ReactNode;
}

/**
 * Provider component for DynamicFormContext.
 * 
 * Simply distributes the centralized state generated by useDynamicForm.
 * It does not maintain any local state, ensuring a single source of truth.
 * All business logic resides in useDynamicForm, while renderers access state here.
 */
export const DynamicFormProvider: React.FC<DynamicFormProviderProps> = ({ value: contextValue, children }) => {
  const value = useMemo(() => contextValue, [contextValue]);

  return (
    <DynamicFormContext.Provider value={value}>
      {children}
    </DynamicFormContext.Provider>
  );
};
