export const DocumentType = {
  COMPANY_PROFILE: 'COMPANY_PROFILE',
  NPWP: 'NPWP',
  NIB: 'NIB',
  AKTA_PENDIRIAN: 'AKTA_PENDIRIAN',
  AKTA_PERUBAHAN: 'AKTA_PERUBAHAN',
  BUSINESS_LICENSE: 'BUSINESS_LICENSE',
  CUSTOMER_REFERENCE: 'CUSTOMER_REFERENCE',
  FINANCIAL_REPORT: 'FINANCIAL_REPORT',
  AUTHORITY_LIMITATION: 'AUTHORITY_LIMITATION',
  OTHER: 'OTHER',
} as const;
