export const Lookup = {
  TITLES: 'TITLES',
  IDENTITY_TYPES: 'IDENTITY_TYPES',
  COUNTRIES: 'COUNTRIES',
  PROVINCES: 'PROVINCES',
  CITIES: 'CITIES',
  BANKS: 'BANKS',
  CURRENCIES: 'CURRENCIES',
  PAYMENT_TERMS: 'PAYMENT_TERMS',
  INDUSTRIES: 'INDUSTRIES',
  JOB_TYPES: 'JOB_TYPES',
} as const;
